// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAiWfdb6Bs_JfFX5OPbutsGqDgEHUOH1g',
    appId: '1:389052377239:web:29d8c7fd8c7e40364221d2',
    messagingSenderId: '389052377239',
    projectId: 'must-fam-admin',
    authDomain: 'must-fam-admin.firebaseapp.com',
    storageBucket: 'must-fam-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSoM8QTMkmH-VjRbmdUTB4wtUMoexAz5Y',
    appId: '1:389052377239:android:7e4d49c2828703694221d2',
    messagingSenderId: '389052377239',
    projectId: 'must-fam-admin',
    storageBucket: 'must-fam-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2nxzSokO0_QrIjERpgUkNpFGX_putEI',
    appId: '1:389052377239:ios:397f3e04c75c5e1a4221d2',
    messagingSenderId: '389052377239',
    projectId: 'must-fam-admin',
    storageBucket: 'must-fam-admin.appspot.com',
    iosBundleId: 'com.example.mustFamSongs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2nxzSokO0_QrIjERpgUkNpFGX_putEI',
    appId: '1:389052377239:ios:60b8c70a930ca4a24221d2',
    messagingSenderId: '389052377239',
    projectId: 'must-fam-admin',
    storageBucket: 'must-fam-admin.appspot.com',
    iosBundleId: 'com.example.mustFamSongs.RunnerTests',
  );
}
